// lib/firebase_options.dart

// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVGGqyGVHu3dTMXBxnioi5xG0OqWNFCyo',
    appId: '1:875416852307:web:00a365a2130da417c3f3a6',
    messagingSenderId: '875416852307',
    projectId: 'movie-drama-log-app',
    authDomain: 'movie-drama-log-app.firebaseapp.com',
    storageBucket: 'movie-drama-log-app.firebasestorage.app',
    measurementId: 'G-33W1NSX5SE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEoKUciNm8QDpW_RsuiHwzACsrBYj_UGs',
    appId: '1:875416852307:android:a016c578d00d4798c3f3a6',
    messagingSenderId: '875416852307',
    projectId: 'movie-drama-log-app',
    storageBucket: 'movie-drama-log-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiXsagaL5PUt6NiPAGUX9bMUKgXtoYh3g',
    appId: '1:875416852307:ios:34c319b0b5e9ef2ec3f3a6',
    messagingSenderId: '875416852307',
    projectId: 'movie-drama-log-app',
    storageBucket: 'movie-drama-log-app.firebasestorage.app',
    iosBundleId: 'com.example.flutterTeamproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiXsagaL5PUt6NiPAGUX9bMUKgXtoYh3g',
    appId: '1:875416852307:ios:34c319b0b5e9ef2ec3f3a6',
    messagingSenderId: '875416852307',
    projectId: 'movie-drama-log-app',
    storageBucket: 'movie-drama-log-app.firebasestorage.app',
    iosBundleId: 'com.example.flutterTeamproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVGGqyGVHu3dTMXBxnioi5xG0OqWNFCyo',
    appId: '1:875416852307:web:43f63d520e418f45c3f3a6',
    messagingSenderId: '875416852307',
    projectId: 'movie-drama-log-app',
    authDomain: 'movie-drama-log-app.firebaseapp.com',
    storageBucket: 'movie-drama-log-app.firebasestorage.app',
    measurementId: 'G-Z67MJH22MQ',
  );
}
